### ISSUE TITLE
Creating LOH for scRNAseq data

### ISSUE THREAD

**Issue by SmritiChawla** [akdess/CaSpER#18]
Hi, thanks for the wonderful tool. Can you please provide tutorial for creation of LOH files for scRNAseq data. It have been mentioned about merging of bam files? Are we supposed to merge all the samples? And in the example it has been mention about sorted file but as a step 1 index file created using samtool index. Can you please clear on this.
Thanks

**Comment by akdess** [comment]
Thanks a lot @Smriti1990  for your interest! 
BAFExtract doesn't require the bam file to be sorted. 
The only tutorial we have right now is here: https://rpubs.com/akdes/578955 
For single cell GBM study in Figure 5, I merged the cells for each patient using the following commands:
bamtools merge -list <bam_file_names> -out <sample_name>_merged.bam
samtools index <sample_name>_merged.bam
And for each patient I ran BAFExtract. You can try different versions such as merging samples by cell type. Hope this helps. But it is in our to do list to create a more detailed tutorial.

You can also ignore BAF shift totally:
after saying CreateCasperObject with parameters: loh.name.mapping=NULL and loh=NULL

Instead of runCasper you can run the following:

final.objects <- list()
loh.list <- list()
cnv.list <- list()

message("Performing HMM segmentation...")

for (i in 1:object@cnv.scale<mailto:object@cnv.scale>) {
cnv.list[[i]] <- PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = F, cytoband = cytoband)
}

for (i in 1:3) {

object <- cnv.list[[i]]

object@segments$states2 <- rep("neut", length(object@segments$state))



object@segments$states2[as.numeric(as.character(object@segments$state)) == 1] <- "del"

object@segments$states2[as.numeric(as.character(object@segments$state)) == 5] <- "amp"

final.objects[[i]] <- generateLargeScaleEvents(object)

}

**Comment by Smriti1990** [comment]
Thank you so very much for you reply. Thanks again

**Comment by SmritiChawla** [comment]
Thank you so much for your reply. Thanks for helping and creating this tool

**Comment by SmritiChawla** [comment]
Is it possible to run Casper for mm10 version. Thanks again

**Comment by Smriti1990** [comment]
I am running this command

for (i in 1:object@cnv.scale) {
  cnv.list[[i]] <- PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = F, cytoband = cytoband)
}

And getting following error:
Error in if (object@segments$size[i] > pair_arm_sizes * (1/3)) object@segments$event_scale[i] <- "large_scale" : 
  missing value where TRUE/FALSE needed

Can you please help me out.
Thanks

**Comment by Smriti1990** [comment]
Hi , I ran this
object <- CreateCasperObject(raw.data=expr,loh.name.mapping=NULL,loh=NULL, sequencing.type="single-cell", 
                             cnv.scale=3, loh.scale=3, matrix.type="normalized", expr.cutoff=4.5,
                             annotation=rannotation, method="iterative", filter="median",  
                             control.sample.ids=control.sample.ids, cytoband=cytoband_hg38,genomeVersion = "hg38")

And I got warning messages:
In runmed(x, filt$n) : 'k' is bigger than 'n'!  Changing 'k' to 99

Is it because loh.name.mapping=NULL and loh=NULL are NULL?

Thanks for helping

**Comment by SmritiChawla** [comment]
Hi , I ran this
object <- CreateCasperObject(raw.data=expr,loh.name.mapping=NULL,loh=NULL, sequencing.type="single-cell", 
                             cnv.scale=3, loh.scale=3, matrix.type="normalized", expr.cutoff=4.5,
                             annotation=rannotation, method="iterative", filter="median",  
                             control.sample.ids=control.sample.ids, cytoband=cytoband_hg38,genomeVersion = "hg38")

And I got warning messages:
In runmed(x, filt$n) : 'k' is bigger than 'n'!  Changing 'k' to 99

Is it because loh.name.mapping=NULL and loh=NULL are NULL?


And one more doubt  about plotSCellCNVTree(), it requires sample name to be mentioned but here we are ignoring loh and loh mapping. Can you please how to plot tree without sample name?

Also when I am trying to replicate plotcnvTree from single cell gbm data, I get this error

plotSCellCNVTree (finalChrMat, sampleName="MGH31", path="./phylip-3.697/exe", fileName="CNVTree.pdf")
Error in (function (classes, fdef, mtable)  : unable to find an inherited method for function ‘distance’ for signature ‘"matrix", "missing"’


Thanks for helping

**Comment by akdess** [comment]
Hi @Smriti1990, I am very sorry for the late reply. Instead of plotSCellCNVTree, I believe simple hierarchial clustering in heatmap for large scale events will also give you some idea. 

finalChrMat <- extractLargeScaleEvents (final.objects, thr=0.75) 

#### VISUALIZATION 
chrMat <- finalChrMat
plot.data <- melt(finalChrMat)
plot.data$value2 <- "neutral"
plot.data$value2[plot.data$value > 0] <- "amplification"
plot.data$value2[plot.data$value < 0] <- "deletion"
plot.data$value2 <- factor(plot.data$value2, levels = c("amplification", 
    "deletion", "neutral"))
plot.data$X2 <- factor(plot.data$X2, levels = colnames(chrMat))
p <- ggplot(aes(x = X2, y = X1, fill = value2), data = plot.data) + 
    geom_tile(colour = "white", size = 0.01) + 
    labs(x = "", 
    y = "") + scale_fill_manual(values = c(amplification = muted("red"), 
    deletion = muted("blue"), neutral = "white")) + theme_grey(base_size = 6) + 
    theme(legend.position = "right", legend.direction = "vertical", 
        legend.title = element_blank(), strip.text.x = element_blank(), 
        legend.text = element_text(colour = "black", size = 7, 
            face = "bold"), legend.key.height = grid::unit(0.8, 
            "cm"), legend.key.width = grid::unit(0.5, "cm"), 
        axis.text.x = element_text(size = 5, colour = "black", 
            angle = -45, hjust = 0), axis.text.y = element_text(size = 6, 
            vjust = 0.2, colour = "black"), axis.ticks = element_line(size = 0.4), 
        plot.title = element_text(colour = "black", hjust = 0, 
            size = 6, face = "bold"))

**Comment by SmritiChawla** [comment]
Thank you so much

**Comment by lifan18** [comment]
Hello @SmritiChawla, Thank you for you raising this question! I am in the same situation too. Was this script correct, `for (i in 1:[object@cnv.scale](mailto:object@cnv.scale)mailto:object@cnv.scale)`? It seems have some typos, but I could not figure out the right one. Could you help me if you know?

All the best!
> Thanks a lot @Smriti1990 for your interest! BAFExtract doesn't require the bam file to be sorted. The only tutorial we have right now is here: https://rpubs.com/akdes/578955 For single cell GBM study in Figure 5, I merged the cells for each patient using the following commands: bamtools merge -list <bam_file_names> -out <sample_name>_merged.bam samtools index <sample_name>_merged.bam And for each patient I ran BAFExtract. You can try different versions such as merging samples by cell type. Hope this helps. But it is in our to do list to create a more detailed tutorial.
> 
> You can also ignore BAF shift totally: after saying CreateCasperObject with parameters: loh.name.mapping=NULL and loh=NULL
> 
> Instead of runCasper you can run the following:
> 
> final.objects <- list() loh.list <- list() cnv.list <- list()
> 
> message("Performing HMM segmentation...")
> 
> for (i in 1:[object@cnv.scale](mailto:object@cnv.scale)[mailto:object@cnv.scale](mailto:object@cnv.scale)) { cnv.list[[i]] <- PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = F, cytoband = cytoband) }
> 
> for (i in 1:3) {
> 
> object <- cnv.list[[i]]
> 
> object@segments$states2 <- rep("neut", length(object@segments$state))
> 
> object@segments$states2[as.numeric(as.character(object@segments$state)) == 1] <- "del"
> 
> object@segments$states2[as.numeric(as.character(object@segments$state)) == 5] <- "amp"
> 
> final.objects[[i]] <- generateLargeScaleEvents(object)
> 
> }

**Comment by lifan18** [comment]
> 

Issue solved. Yes, those were just little typos. See the codes below ;)

```
final.objects <- list()
loh.list <- list()
cnv.list <- list()

message("Performing HMM segmentation...")

for (i in 1:object@cnv.scale) {
    cnv.list[[i]] <- PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = F, cytoband = cytoband)

}
for (i in 1:3) {

object <- cnv.list[[i]]

object@segments$states2 <- rep("neut", length(object@segments$state))

object@segments$states2[as.numeric(as.character(object@segments$state)) == 1] <- "del"

object@segments$states2[as.numeric(as.character(object@segments$state)) == 5] <- "amp"

final.objects[[i]] <- generateLargeScaleEvents(object)

}
```
