### ISSUE TITLE
analysis of smart-seq2 data

### ISSUE THREAD

**Issue by Svanuytven** [akdess/CaSpER#22]
Dear authors,

Thank you very much for creating an excellent tool to investigate genomic heterogeneity with scRNA-seq. I was wondering if you could help me to find the optimal strategy to analyse a cancer cell dataset obtained using the smart-seq2 protocol. My sample contains 288 cancer cells and I also have normal cells of another dataset that I can use as a reference, but I’m also planning on testing Gtex data as reference.

My questions are
-	Should I normalize both datasets (cancer dataset and reference dataset) together or separately? Any recommendations for the normalization if I would use a bulk sample as reference
-	Do I need to create the LOH file for each SS2 sample separately or should I do it for the combined bam file? If so, do I also need to merge the normal samples before running the pileup? Or do I need the run the pileup separately for my normal cells?
-	Are there maybe future plans to release your tool as a docker image?

Thank you very much in advance and apologies for the excessive amount of questions

Seb.

**Comment by akdess** [comment]
Dear @Svanuytven, 

Thanks a lot for using our tool. I would be glad to help you. 
1. Does your single cell data contain any immune cells? Those would be the best control. You can also use another dataset. I would  use the updated Casper version where you can also input raw counts data. You can combine the datasets and give the raw unnormalized counts as input. Use the genes that are only present in both datasets. In CreateCasperObject function you should use matrix.type="raw" parameter. We are planning to update the documentation for the recent changes soon. 

2. You don't need to run pileup for normal cells if you are not interested in the normal cell CNV calls. Our experience is that usually there is not enough BAF signal in one single cell. I would recommend combining all the samples as one bam file. You can also skip the BAF signal step and only identify CNV based on the expression signal. 

you can ignore BAF shift: 
after saying CreateCasperObject with parameters: loh.name.mapping=NULL and loh=NULL
Instead of runCasper you can run the following:

final.objects <- list()
loh.list <- list()
cnv.list <- list()

message("Performing HMM segmentation...")

for (i in 1:object@cnv.scale) {
cnv.list[[i]] <- PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = F, cytoband = cytoband)
}

for (i in 1:3) {

object <- cnv.list[[i]]
object@segments$states2 <- rep("neut", length(object@segments$state))

object@segments$states2[as.numeric(as.character(object@segments$state)) == 1] <- "del"
object@segments$states2[as.numeric(as.character(object@segments$state)) == 5] <- "amp"
final.objects[[i]] <- generateLargeScaleEvents(object)
}

3. We would like to update the code and documentation soon. Docker image is also in our to do list. 

Thanks a lot for your interest. I am also happy to look at your R data if you ran into some issues. 

Best,
Akdes

**Comment by Svanuytven** [comment]
Dear Dr. Harmanci,

Thank you very much for your fast and extensive answer to all my questions. Based on the information, i managed to get to runCaSpER step for single-cell data where i get the following error "Error in if (G[1] == 1) { : missing value where TRUE/FALSE needed". Could you maybe suggest what could be the reason for this problem?

If it would be necessary to seed the R data, please let me know what the best way would be to send it to you.

Kind regards,

Sebastiaan

**Comment by akdess** [comment]
Dear @Svanuytven, I am not sure exactly what the error is but I can try understand if you can send me your rdata. akdess at gmail com. 

Thanks a lot for your interest!
Akdes
